### ISSUE TITLE
data lost

### ISSUE THREAD

**Issue by frallisland** [plcrodrigues/py.BI.EEG.2015a-GIPSA#2]
It just have 43 subjects' EEG signak in the [dataset link](https://zenodo.org/record/3266930),please tell me the position which the rest of datasets in?

**Comment by gcattan** [comment]
Hi. 
In general, the organisation of the dataset is described in https://hal.archives-ouvertes.fr/hal-02172347:


"Among the 50 pairs of participants, 9 have been rejected from the study for the following reasons:

Participant 1, 45, 48, 49, 50 couldn’t finish the experiment due lack of sufficient powering of the pre-amplifier.
Participant 47: vision not perfectly corrected with binoculars.
Participant 27, 46: no visible occipital dominant rhythm during installation.
Participant 44: corrupted data

The data of subject 1 and 27 are provided as they can be of general interest, however the rejected data should not be used for BCI meta-analysis."

**Comment by frallisland** [comment]
thank you for the answer

**Comment by gcattan** [comment]
You are welcome.
I am closing this issue, feel free to reopen it if you have further issues.
